[package]
name = "mhws-tex-decompressor"
version = "0.3.2"
edition = "2024"

[dependencies]
# # local development
# re-tex = { path = "../re-tex" }
# ree-pak-core = { path = "../../ree-pak-rs/ree-pak-core" }

re-tex = { git = "https://github.com/eigeen/re-tex.git", rev = "64f85bc" }
ree-pak-core = { git = "https://github.com/eigeen/ree-pak-rs.git", rev = "6dad4ae", package = "ree-pak-core" }

# UI
dialoguer = "0.12"
indicatif = "0.18"
colored = "3.1"

color-eyre = "0.6"
parking_lot = "0.12"
fs-err = "3.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.49", features = [
    "parking_lot",
    "rt-multi-thread",
    "macros",
] }
iocraft = "0.7"
reqwest = { version = "0.13", features = ["json"] }
semver = "1.0"
self-replace = "1.5"
tempfile = "3.25"
zip = { version = "8.1", default-features = false, features = ["deflate"] }
